### ISSUE TITLE
This authorization code has been used.

### ISSUE THREAD

**Issue by chriz001** [ptariche/SailsJS-Facebook-Example#1]
Hi, thanks for this example. Im just trying to get it up and running, but im unable to do so on the live server.

i get the following error twice.

error: FacebookTokenError: This authorization code has been used.

do you have any suggestions about how to deal with this?

**Comment by ptariche** [comment]
This is due to a callback error. Are you visiting the Facebook authorization page twice? The second time it may have stored a false authorization code.

**Comment by chriz001** [comment]
I only did it once and it gave the error. I git cloned to my server, updated the facebook settings and changed to the sails-memory data store for testing. 

Have you got it working on a production server? or just locally?

**Comment by ptariche** [comment]
Still having a problem? Did you change the adapters?

**Comment by chriz001** [comment]
Yeah, still doesn't work for me. I changed the adapter to use sails-memory instead of mongo.
